# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
use_frameworks!
target 'CountryPicker_Example' do
#    pod 'CountryPickerSwift'
    pod 'CountryPickerSwift', :path => '../'
  target 'CountryPicker_Tests' do
    inherit! :search_paths

    
  end

end
