//
//  ViewController.swift
//  CountryPicker
//
//  Created by 4taras4 on 12/02/2016.
//  Copyright (c) 2016 4taras4. All rights reserved.
//

import CountryPicker
import UIKit

class ViewController: UIViewController, CountryPickerDelegate {
    @IBOutlet var picker: CountryPicker!
    @IBOutlet var code: UILabel!

    override func viewDidLoad() {
        super.viewDidLoad()

        // get corrent country
        let locale = Locale.current
        let code = (locale as NSLocale).object(forKey: NSLocale.Key.countryCode) as! String?

        // init Picker

        picker.countryPickerDelegate = self
        picker.showPhoneNumbers = true

        // optional settings

        // data source
        /**
        picker.countries = customCountries
         */

        // theme
        /**
         let theme = CountryViewTheme(
             countryCodeTextColor: .white,
             countryNameTextColor: .white,
             rowBackgroundColor: .black
         )
         picker.theme = theme
         */

        picker.setCountry(code!)
    }

    // MARK: - CountryPhoneCodePickerDelegate

    public func countryPhoneCodePicker(_ picker: CountryPicker, didSelect country: Country) {
        code.text = country.phoneCode
    }

    private var customCountries: [Country] {
        return [
            Country(code: "AD", name: "Angola", phoneCode: "+244", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ad.png"),
            Country(code: "AF", name: "Afghanistan", phoneCode: "+93", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/af.png"),
            Country(code: "AL", name: "Albania", phoneCode: "+355", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/al.png"),
            Country(code: "DZ", name: "Algeria", phoneCode: "+213", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/dz.png"),
            Country(code: "AS", name: "American Samoa", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/as.png"),
            Country(code: "AD", name: "Andorra", phoneCode: "+376", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ad.png"),
            Country(code: "AO", name: "Angola", phoneCode: "+244", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ao.png"),
            Country(code: "AI", name: "Anguilla", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ai.png"),
            Country(code: "AG", name: "Antigua & Barbuda", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ag.png"),
            Country(code: "AR", name: "Argentina", phoneCode: "+54", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ar.png"),
            Country(code: "AM", name: "Armenia", phoneCode: "+374", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/am.png"),
            Country(code: "AW", name: "Aruba", phoneCode: "+297", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/aw.png"),
            Country(code: "AC", name: "Ascension Island", phoneCode: "+247", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ac.png"),
            Country(code: "AU", name: "Australia", phoneCode: "+61", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/au.png"),
            Country(code: "AT", name: "Austria", phoneCode: "+43", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/at.png"),
            Country(code: "AZ", name: "Azerbaijan", phoneCode: "+994", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/az.png"),
            Country(code: "BS", name: "Bahamas", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/bs.png"),
            Country(code: "BH", name: "Bahrain", phoneCode: "+973", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/bh.png"),
            Country(code: "BD", name: "Bangladesh", phoneCode: "+880", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/bd.png"),
            Country(code: "BB", name: "Barbados", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/bb.png"),
            Country(code: "BY", name: "Belarus", phoneCode: "+375", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/by.png"),
            Country(code: "BE", name: "Belgium", phoneCode: "+32", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/be.png"),
            Country(code: "BZ", name: "Belize", phoneCode: "+501", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/bz.png"),
            Country(code: "BJ", name: "Benin", phoneCode: "+229", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/bj.png"),
            Country(code: "BM", name: "Bermuda", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/bm.png"),
            Country(code: "BT", name: "Bhutan", phoneCode: "+975", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/bt.png"),
            Country(code: "BO", name: "Bolivia", phoneCode: "+591", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/bo.png"),
            Country(code: "BA", name: "Bosnia & Herzegovina", phoneCode: "+387", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ba.png"),
            Country(code: "BW", name: "Botswana", phoneCode: "+267", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/bw.png"),
            Country(code: "BR", name: "Brazil", phoneCode: "+55", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/br.png"),
            Country(code: "IO", name: "British Indian Ocean Territory", phoneCode: "+246", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/io.png"),
            Country(code: "VG", name: "British Virgin Islands", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/vg.png"),
            Country(code: "BN", name: "Brunei", phoneCode: "+673", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/bn.png"),
            Country(code: "BG", name: "Bulgaria", phoneCode: "+359", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/bg.png"),
            Country(code: "BF", name: "Burkina Faso", phoneCode: "+226", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/bf.png"),
            Country(code: "BI", name: "Burundi", phoneCode: "+257", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/bi.png"),
            Country(code: "KH", name: "Cambodia", phoneCode: "+855", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/kh.png"),
            Country(code: "CM", name: "Cameroon", phoneCode: "+237", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/cm.png"),
            Country(code: "CA", name: "Canada", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ca.png"),
            Country(code: "CV", name: "Cape Verde", phoneCode: "+238", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/cv.png"),
            Country(code: "BQ", name: "Caribbean Netherlands", phoneCode: "+599", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/bq.png"),
            Country(code: "KY", name: "Cayman Islands", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ky.png"),
            Country(code: "CF", name: "Central African Republic", phoneCode: "+236", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/cf.png"),
            Country(code: "TD", name: "Chad", phoneCode: "+235", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/td.png"),
            Country(code: "CL", name: "Chile", phoneCode: "+56", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/cl.png"),
            Country(code: "CN", name: "China", phoneCode: "+86", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/cn.png"),
            Country(code: "CO", name: "Colombia", phoneCode: "+57", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/co.png"),
            Country(code: "KM", name: "Comoros", phoneCode: "+269", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/km.png"),
            Country(code: "CG", name: "Congo - Brazzaville", phoneCode: "+242", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/cg.png"),
            Country(code: "CD", name: "Congo - Kinshasa", phoneCode: "+243", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/cd.png"),
            Country(code: "CK", name: "Cook Islands", phoneCode: "+682", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ck.png"),
            Country(code: "CR", name: "Costa Rica", phoneCode: "+506", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/cr.png"),
            Country(code: "CI", name: "Côte d’Ivoire", phoneCode: "+225", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ci.png"),
            Country(code: "HR", name: "Croatia", phoneCode: "+385", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/hr.png"),
            Country(code: "CU", name: "Cuba", phoneCode: "+53", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/cu.png"),
            Country(code: "CW", name: "Curaçao", phoneCode: "+599", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/cw.png"),
            Country(code: "CY", name: "Cyprus", phoneCode: "+357", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/cy.png"),
            Country(code: "CZ", name: "Czechia", phoneCode: "+420", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/cz.png"),
            Country(code: "DK", name: "Denmark", phoneCode: "+45", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/dk.png"),
            Country(code: "DJ", name: "Djibouti", phoneCode: "+253", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/dj.png"),
            Country(code: "DM", name: "Dominica", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/dm.png"),
            Country(code: "DO", name: "Dominican Republic", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/do.png"),
            Country(code: "EC", name: "Ecuador", phoneCode: "+593", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ec.png"),
            Country(code: "EG", name: "Egypt", phoneCode: "+20", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/eg.png"),
            Country(code: "SV", name: "El Salvador", phoneCode: "+503", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/sv.png"),
            Country(code: "GQ", name: "Equatorial Guinea", phoneCode: "+240", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/gq.png"),
            Country(code: "ER", name: "Eritrea", phoneCode: "+291", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/er.png"),
            Country(code: "EE", name: "Estonia", phoneCode: "+372", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ee.png"),
            Country(code: "ET", name: "Ethiopia", phoneCode: "+251", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/et.png"),
            Country(code: "FK", name: "Falkland Islands (Islas Malvinas)", phoneCode: "+500", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/fk.png"),
            Country(code: "FO", name: "Faroe Islands", phoneCode: "+298", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/fo.png"),
            Country(code: "FJ", name: "Fiji", phoneCode: "+679", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/fj.png"),
            Country(code: "FI", name: "Finland", phoneCode: "+358", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/fi.png"),
            Country(code: "FR", name: "France", phoneCode: "+33", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/fr.png"),
            Country(code: "GF", name: "French Guiana", phoneCode: "+594", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/gf.png"),
            Country(code: "PF", name: "French Polynesia", phoneCode: "+689", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/pf.png"),
            Country(code: "GA", name: "Gabon", phoneCode: "+241", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ga.png"),
            Country(code: "GM", name: "Gambia", phoneCode: "+220", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/gm.png"),
            Country(code: "GE", name: "Georgia", phoneCode: "+995", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ge.png"),
            Country(code: "DE", name: "Germany", phoneCode: "+49", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/de.png"),
            Country(code: "GH", name: "Ghana", phoneCode: "+233", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/gh.png"),
            Country(code: "GI", name: "Gibraltar", phoneCode: "+350", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/gi.png"),
            Country(code: "GR", name: "Greece", phoneCode: "+30", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/gr.png"),
            Country(code: "GL", name: "Greenland", phoneCode: "+299", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/gl.png"),
            Country(code: "GD", name: "Grenada", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/gd.png"),
            Country(code: "GP", name: "Guadeloupe", phoneCode: "+590", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/gp.png"),
            Country(code: "GU", name: "Guam", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/gu.png"),
            Country(code: "GT", name: "Guatemala", phoneCode: "+502", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/gt.png"),
            Country(code: "GN", name: "Guinea", phoneCode: "+224", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/gn.png"),
            Country(code: "GW", name: "Guinea-Bissau", phoneCode: "+245", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/gw.png"),
            Country(code: "GY", name: "Guyana", phoneCode: "+592", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/gy.png"),
            Country(code: "HT", name: "Haiti", phoneCode: "+509", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ht.png"),
            Country(code: "HN", name: "Honduras", phoneCode: "+504", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/hn.png"),
            Country(code: "HK", name: "Hong Kong", phoneCode: "+852", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/hk.png"),
            Country(code: "HU", name: "Hungary", phoneCode: "+36", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/hu.png"),
            Country(code: "IS", name: "Iceland", phoneCode: "+354", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/is.png"),
            Country(code: "IN", name: "India", phoneCode: "+91", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/in.png"),
            Country(code: "ID", name: "Indonesia", phoneCode: "+62", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/id.png"),
            Country(code: "IR", name: "Iran", phoneCode: "+98", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ir.png"),
            Country(code: "IQ", name: "Iraq", phoneCode: "+964", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/iq.png"),
            Country(code: "IE", name: "Ireland", phoneCode: "+353", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ie.png"),
            Country(code: "IL", name: "Israel", phoneCode: "+972", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/il.png"),
            Country(code: "IT", name: "Italy", phoneCode: "+39", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/it.png"),
            Country(code: "JM", name: "Jamaica", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/jm.png"),
            Country(code: "JP", name: "Japan", phoneCode: "+81", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/jp.png"),
            Country(code: "JO", name: "Jordan", phoneCode: "+962", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/jo.png"),
            Country(code: "KZ", name: "Kazakhstan", phoneCode: "+7", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/kz.png"),
            Country(code: "KE", name: "Kenya", phoneCode: "+254", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ke.png"),
            Country(code: "KI", name: "Kiribati", phoneCode: "+686", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ki.png"),
            Country(code: "XK", name: "Kosovo", phoneCode: "+383", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/xk.png"),
            Country(code: "KW", name: "Kuwait", phoneCode: "+965", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/kw.png"),
            Country(code: "KG", name: "Kyrgyzstan", phoneCode: "+996", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/kg.png"),
            Country(code: "LA", name: "Laos", phoneCode: "+856", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/la.png"),
            Country(code: "LV", name: "Latvia", phoneCode: "+371", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/lv.png"),
            Country(code: "LB", name: "Lebanon", phoneCode: "+961", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/lb.png"),
            Country(code: "LS", name: "Lesotho", phoneCode: "+266", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ls.png"),
            Country(code: "LR", name: "Liberia", phoneCode: "+231", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/lr.png"),
            Country(code: "LY", name: "Libya", phoneCode: "+218", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ly.png"),
            Country(code: "LI", name: "Liechtenstein", phoneCode: "+423", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/li.png"),
            Country(code: "LT", name: "Lithuania", phoneCode: "+370", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/lt.png"),
            Country(code: "LU", name: "Luxembourg", phoneCode: "+352", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/lu.png"),
            Country(code: "MO", name: "Macau", phoneCode: "+853", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/mo.png"),
            Country(code: "MK", name: "Macedonia (FYROM)", phoneCode: "+389", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/mk.png"),
            Country(code: "MG", name: "Madagascar", phoneCode: "+261", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/mg.png"),
            Country(code: "MW", name: "Malawi", phoneCode: "+265", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/mw.png"),
            Country(code: "MY", name: "Malaysia", phoneCode: "+60", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/my.png"),
            Country(code: "MV", name: "Maldives", phoneCode: "+960", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/mv.png"),
            Country(code: "ML", name: "Mali", phoneCode: "+223", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ml.png"),
            Country(code: "MT", name: "Malta", phoneCode: "+356", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/mt.png"),
            Country(code: "MH", name: "Marshall Islands", phoneCode: "+692", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/mh.png"),
            Country(code: "MQ", name: "Martinique", phoneCode: "+596", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/mq.png"),
            Country(code: "MR", name: "Mauritania", phoneCode: "+222", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/mr.png"),
            Country(code: "MU", name: "Mauritius", phoneCode: "+230", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/mu.png"),
            Country(code: "MX", name: "Mexico", phoneCode: "+52", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/mx.png"),
            Country(code: "FM", name: "Micronesia", phoneCode: "+691", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/fm.png"),
            Country(code: "MD", name: "Moldova", phoneCode: "+373", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/md.png"),
            Country(code: "MC", name: "Monaco", phoneCode: "+377", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/mc.png"),
            Country(code: "MN", name: "Mongolia", phoneCode: "+976", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/mn.png"),
            Country(code: "ME", name: "Montenegro", phoneCode: "+382", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/me.png"),
            Country(code: "MS", name: "Montserrat", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ms.png"),
            Country(code: "MA", name: "Morocco", phoneCode: "+212", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ma.png"),
            Country(code: "MZ", name: "Mozambique", phoneCode: "+258", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/mz.png"),
            Country(code: "MM", name: "Myanmar (Burma)", phoneCode: "+95", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/mm.png"),
            Country(code: "NA", name: "Namibia", phoneCode: "+264", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/na.png"),
            Country(code: "NR", name: "Nauru", phoneCode: "+674", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/nr.png"),
            Country(code: "NP", name: "Nepal", phoneCode: "+977", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/np.png"),
            Country(code: "NL", name: "Netherlands", phoneCode: "+31", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/nl.png"),
            Country(code: "NC", name: "New Caledonia", phoneCode: "+687", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/nc.png"),
            Country(code: "NZ", name: "New Zealand", phoneCode: "+64", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/nz.png"),
            Country(code: "NI", name: "Nicaragua", phoneCode: "+505", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ni.png"),
            Country(code: "NE", name: "Niger", phoneCode: "+227", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ne.png"),
            Country(code: "NG", name: "Nigeria", phoneCode: "+234", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ng.png"),
            Country(code: "NU", name: "Niue", phoneCode: "+683", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/nu.png"),
            Country(code: "NF", name: "Norfolk Island", phoneCode: "+672", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/nf.png"),
            Country(code: "KP", name: "North Korea", phoneCode: "+850", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/kp.png"),
            Country(code: "MP", name: "Northern Mariana Islands", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/mp.png"),
            Country(code: "NO", name: "Norway", phoneCode: "+47", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/no.png"),
            Country(code: "OM", name: "Oman", phoneCode: "+968", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/om.png"),
            Country(code: "PK", name: "Pakistan", phoneCode: "+92", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/pk.png"),
            Country(code: "PW", name: "Palau", phoneCode: "+680", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/pw.png"),
            Country(code: "PS", name: "Palestine", phoneCode: "+970", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ps.png"),
            Country(code: "PA", name: "Panama", phoneCode: "+507", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/pa.png"),
            Country(code: "PG", name: "Papua New Guinea", phoneCode: "+675", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/pg.png"),
            Country(code: "PY", name: "Paraguay", phoneCode: "+595", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/py.png"),
            Country(code: "PE", name: "Peru", phoneCode: "+51", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/pe.png"),
            Country(code: "PH", name: "Philippines", phoneCode: "+63", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ph.png"),
            Country(code: "PL", name: "Poland", phoneCode: "+48", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/pl.png"),
            Country(code: "PT", name: "Portugal", phoneCode: "+351", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/pt.png"),
            Country(code: "PR", name: "Puerto Rico", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/pr.png"),
            Country(code: "QA", name: "Qatar", phoneCode: "+974", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/qa.png"),
            Country(code: "RE", name: "Réunion", phoneCode: "+262", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/re.png"),
            Country(code: "RO", name: "Romania", phoneCode: "+40", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ro.png"),
            Country(code: "RU", name: "Russia", phoneCode: "+7", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ru.png"),
            Country(code: "RW", name: "Rwanda", phoneCode: "+250", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/rw.png"),
            Country(code: "WS", name: "Samoa", phoneCode: "+685", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ws.png"),
            Country(code: "SM", name: "San Marino", phoneCode: "+378", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/sm.png"),
            Country(code: "ST", name: "São Tomé & Príncipe", phoneCode: "+239", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/st.png"),
            Country(code: "SA", name: "Saudi Arabia", phoneCode: "+966", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/sa.png"),
            Country(code: "SN", name: "Senegal", phoneCode: "+221", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/sn.png"),
            Country(code: "RS", name: "Serbia", phoneCode: "+381", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/rs.png"),
            Country(code: "SC", name: "Seychelles", phoneCode: "+248", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/sc.png"),
            Country(code: "SL", name: "Sierra Leone", phoneCode: "+232", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/sl.png"),
            Country(code: "SG", name: "Singapore", phoneCode: "+65", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/sg.png"),
            Country(code: "SX", name: "Sint Maarten", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/sx.png"),
            Country(code: "SK", name: "Slovakia", phoneCode: "+421", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/sk.png"),
            Country(code: "SI", name: "Slovenia", phoneCode: "+386", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/si.png"),
            Country(code: "SB", name: "Solomon Islands", phoneCode: "+677", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/sb.png"),
            Country(code: "SO", name: "Somalia", phoneCode: "+252", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/so.png"),
            Country(code: "ZA", name: "South Africa", phoneCode: "+27", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/za.png"),
            Country(code: "KR", name: "South Korea", phoneCode: "+82", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/kr.png"),
            Country(code: "SS", name: "South Sudan", phoneCode: "+211", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ss.png"),
            Country(code: "ES", name: "Spain", phoneCode: "+34", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/es.png"),
            Country(code: "LK", name: "Sri Lanka", phoneCode: "+94", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/lk.png"),
            Country(code: "BL", name: "St. Barthélemy", phoneCode: "+590", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/bl.png"),
            Country(code: "SH", name: "St. Helena", phoneCode: "+290", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/sh.png"),
            Country(code: "KN", name: "St. Kitts & Nevis", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/kn.png"),
            Country(code: "LC", name: "St. Lucia", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/lc.png"),
            Country(code: "MF", name: "St. Martin", phoneCode: "+590", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/mf.png"),
            Country(code: "PM", name: "St. Pierre & Miquelon", phoneCode: "+508", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/pm.png"),
            Country(code: "VC", name: "St. Vincent & Grenadines", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/vc.png"),
            Country(code: "SD", name: "Sudan", phoneCode: "+249", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/sd.png"),
            Country(code: "SR", name: "Suriname", phoneCode: "+597", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/sr.png"),
            Country(code: "SZ", name: "Swaziland", phoneCode: "+268", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/sz.png"),
            Country(code: "SE", name: "Sweden", phoneCode: "+46", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/se.png"),
            Country(code: "CH", name: "Switzerland", phoneCode: "+41", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ch.png"),
            Country(code: "SY", name: "Syria", phoneCode: "+963", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/sy.png"),
            Country(code: "TW", name: "Taiwan", phoneCode: "+886", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/tw.png"),
            Country(code: "TJ", name: "Tajikistan", phoneCode: "+992", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/tj.png"),
            Country(code: "TZ", name: "Tanzania", phoneCode: "+255", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/tz.png"),
            Country(code: "TH", name: "Thailand", phoneCode: "+66", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/th.png"),
            Country(code: "TL", name: "Timor-Leste", phoneCode: "+670", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/tl.png"),
            Country(code: "TG", name: "Togo", phoneCode: "+228", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/tg.png"),
            Country(code: "TK", name: "Tokelau", phoneCode: "+690", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/tk.png"),
            Country(code: "TO", name: "Tonga", phoneCode: "+676", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/to.png"),
            Country(code: "TT", name: "Trinidad & Tobago", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/tt.png"),
            Country(code: "TN", name: "Tunisia", phoneCode: "+216", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/tn.png"),
            Country(code: "TR", name: "Turkey", phoneCode: "+90", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/tr.png"),
            Country(code: "TM", name: "Turkmenistan", phoneCode: "+993", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/tm.png"),
            Country(code: "TC", name: "Turks & Caicos Islands", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/tc.png"),
            Country(code: "TV", name: "Tuvalu", phoneCode: "+688", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/tv.png"),
            Country(code: "VI", name: "U.S. Virgin Islands", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/vi.png"),
            Country(code: "UG", name: "Uganda", phoneCode: "+256", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ug.png"),
            Country(code: "UA", name: "Ukraine", phoneCode: "+380", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ua.png"),
            Country(code: "AE", name: "United Arab Emirates", phoneCode: "+971", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ae.png"),
            Country(code: "GB", name: "United Kingdom", phoneCode: "+44", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/gb.png"),
            Country(code: "US", name: "United States", phoneCode: "+1", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/us.png"),
            Country(code: "UY", name: "Uruguay", phoneCode: "+598", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/uy.png"),
            Country(code: "UZ", name: "Uzbekistan", phoneCode: "+998", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/uz.png"),
            Country(code: "VU", name: "Vanuatu", phoneCode: "+678", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/vu.png"),
            Country(code: "VA", name: "Vatican City", phoneCode: "+39", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/va.png"),
            Country(code: "VE", name: "Venezuela", phoneCode: "+58", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ve.png"),
            Country(code: "VN", name: "Vietnam", phoneCode: "+84", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/vn.png"),
            Country(code: "WF", name: "Wallis & Futuna", phoneCode: "+681", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/wf.png"),
            Country(code: "YE", name: "Yemen", phoneCode: "+967", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/ye.png"),
            Country(code: "ZM", name: "Zambia", phoneCode: "+260", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/zm.png"),
            Country(code: "ZW", name: "Zimbabwe", phoneCode: "+263", flagURLString: "https://stag-country-data.3ona.co/country_data/flag_images/zw.png"),
        ]
    }
}
